# Generated by Django 2.1.5 on 2019-11-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191128_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Assignment'),
        ),
    ]
